version: '3.8'

services:
  registry:
    image: registry:2
    networks:
      - traefik-public
    volumes:
      - data:/var/lib/registry
      - auth:/auth
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.http.services.registry-registry.loadbalancer.server.port=5000
        - traefik.http.routers.registry.rule=Host(`registry.yosemitesam.ch`)
        - traefik.http.routers.registry.entrypoints=https
        - traefik.http.routers.registry.tls.certresolver=le
        - traefik.http.routers.registry.tls=true
          # Basic auth with custom registry users
        - traefik.http.middlewares.registry-auth.basicauth.usersfile=/auth/registry.passwd
        # I'm actually not sure if the following is necessary, but it's more or less what they recommend in the nginx/apache settings
        #- traefik.http.middlewares.registry-auth.basicauth.removeheader=true
        - traefik.http.middlewares.registry-headers.headers.contentTypeNosniff=true
        - traefik.http.middlewares.registry-headers.headers.customrequestheaders.Docker-Distribution-Api-Version=registry/2.0
        - traefik.http.middlewares.registry-headers.headers.customresponseheaders.Docker-Distribution-Api-Version=registry/2.0
          #        - traefik.http.middlewares.registry.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.registry.headers.hostsProxyHeaders=true
        - traefik.http.routers.registry.middlewares=registry-auth,registry-headers
    # A user interface for my registry :)
networks:
  traefik-public:
    external: true

volumes:
  data:
  auth:
